# Generated by Django 3.2.19 on 2025-12-30 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingaccount',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='server',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
