# Generated by Django 3.2.19 on 2026-01-09 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20251230_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='name',
            field=models.CharField(default='Unnamed Robot', max_length=100),
        ),
        migrations.AddField(
            model_name='robot',
            name='python_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='robot',
            name='strategy_class',
            field=models.CharField(choices=[('RULE', 'Rule-Based Strategy'), ('OPTIMIZED_RULE', 'Optimized Rule Strategy'), ('ML', 'Machine-Learning Strategy')], default='RULE', max_length=20),
        ),
        migrations.AddField(
            model_name='robot',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='TradeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('action', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('profit', models.FloatField(default=0.0)),
                ('latency', models.FloatField(blank=True, null=True)),
                ('slippage', models.FloatField(blank=True, null=True)),
                ('spread', models.FloatField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('robot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.robot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RobotBuildTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('BUILDING', 'Building'), ('FAILED', 'Failed'), ('COMPLETE', 'Complete')], default='PENDING', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_tasks', to='api.robot')),
            ],
        ),
        migrations.CreateModel(
            name='StrategyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('indicators', models.JSONField()),
                ('risk_settings', models.JSONField()),
                ('mql5_code', models.TextField(blank=True, null=True)),
                ('python_code', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='api.robot')),
            ],
            options={
                'unique_together': {('robot', 'version_number')},
            },
        ),
    ]
