# Generated by Django 3.2.19 on 2026-01-09 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20260109_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('parameters', models.JSONField(default=dict)),
                ('mql5_snippet', models.TextField()),
                ('python_snippet', models.TextField()),
                ('ui_flags', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RobotEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('DEPLOYED', 'Deployed'), ('TRADE_EXECUTED', 'Trade Executed'), ('ERROR', 'Error'), ('STOPPED', 'Stopped'), ('UPDATED', 'Updated')], max_length=20)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.robot')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyKillSwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('TRIGGERED', 'Triggered'), ('RESOLVED', 'Resolved')], default='ACTIVE', max_length=20)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('close_positions', models.BooleanField(default=False)),
                ('revoke_mt5_access', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kill_switches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeploymentValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('PREFLIGHT', 'Preflight Validation'), ('INJECTION', 'Code Injection'), ('CONFIRMATION', 'Execution Confirmation')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('mt5_terminal_reachable', models.BooleanField(default=False)),
                ('account_authorized', models.BooleanField(default=False)),
                ('symbol_exists', models.BooleanField(default=False)),
                ('lot_size_allowed', models.BooleanField(default=False)),
                ('ea_attached', models.BooleanField(default=False)),
                ('heartbeat_received', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployment_validations', to='api.robot')),
            ],
        ),
        migrations.CreateModel(
            name='AccountGuardrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_daily_loss', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('max_concurrent_positions', models.IntegerField(default=3)),
                ('max_correlation_exposure', models.FloatField(default=0.7)),
                ('daily_loss_current', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_reset', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guardrails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
