# Generated by Django 3.2.19 on 2026-01-16 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_accountguardrail_deploymentvalidation_emergencykillswitch_indicatortemplate_robotevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appvisit',
            old_name='timestamp',
            new_name='visit_time',
        ),
        migrations.RemoveField(
            model_name='appvisit',
            name='page_visited',
        ),
        migrations.RemoveField(
            model_name='tradingaccount',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='tradingaccount',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='tradingaccount',
            name='equity',
        ),
        migrations.RemoveField(
            model_name='tradingaccount',
            name='lot_size',
        ),
        migrations.RemoveField(
            model_name='tradingaccount',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='tradingaccount',
            name='password',
        ),
        migrations.RemoveField(
            model_name='tradingaccount',
            name='server',
        ),
        migrations.RemoveField(
            model_name='tradingaccount',
            name='status',
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_broker',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='robot',
            name='confidence_threshold',
            field=models.FloatField(default=0.6),
        ),
        migrations.AddField(
            model_name='robot',
            name='historical_lookback',
            field=models.IntegerField(choices=[(1, '1 Month'), (3, '3 Months'), (6, '6 Months'), (12, '1 Year'), (24, '2 Years')], default=3),
        ),
        migrations.AddField(
            model_name='robot',
            name='max_entry_wait_minutes',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='robot',
            name='recency_bias',
            field=models.FloatField(default=0.1, help_text='Lambda value for time weighting'),
        ),
        migrations.AddField(
            model_name='robot',
            name='session_preference',
            field=models.CharField(choices=[('ANY', 'Any Session'), ('LONDON', 'London'), ('NY', 'New York'), ('ASIA', 'Asia')], default='ANY', max_length=10),
        ),
        migrations.AddField(
            model_name='robot',
            name='training_data_source',
            field=models.CharField(choices=[('MT5', 'MetaTrader 5'), ('YFINANCE', 'Yahoo Finance'), ('MIXED', 'Mixed Sources'), ('NONE', 'Not Trained')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='tradelog',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradelog',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tradelog',
            name='entry_type',
            field=models.CharField(choices=[('MARKET', 'Market'), ('BUY_LIMIT', 'Buy Limit'), ('SELL_LIMIT', 'Sell Limit'), ('BUY_STOP', 'Buy Stop'), ('SELL_STOP', 'Sell Stop')], default='MARKET', max_length=20),
        ),
        migrations.AddField(
            model_name='tradelog',
            name='expiry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradelog',
            name='final_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tradelog',
            name='initial_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tradelog',
            name='sl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradelog',
            name='status',
            field=models.CharField(choices=[('IDLE', 'Idle'), ('ANALYZING', 'Analyzing History'), ('ORDER_PLACED', 'Conditional Order Placed'), ('TRIGGERED', 'Order Triggered'), ('CLOSED', 'Trade Closed'), ('EXPIRED', 'Order Expired'), ('FAILED', 'Failed')], default='IDLE', max_length=20),
        ),
        migrations.AddField(
            model_name='tradelog',
            name='target_entry',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradelog',
            name='tp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradelog',
            name='triggered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='broker',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='is_demo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='mt5_login',
            field=models.CharField(default='000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='mt5_password',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='mt5_server',
            field=models.CharField(default='MetaQuotes-Demo', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appvisit',
            name='ip_address',
            field=models.CharField(default='127.0.0.1', max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='latency',
            field=models.FloatField(blank=True, help_text='Execution latency in ms', null=True),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='robot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='api.robot'),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='slippage',
            field=models.FloatField(blank=True, help_text='Slippage in pips', null=True),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='symbol',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tradingaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mt5_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RobotBuildReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('PARTIAL', 'Partial Success (Warnings)'), ('FAILED', 'Failed')], max_length=20)),
                ('data_source', models.CharField(choices=[('MT5', 'MetaTrader 5'), ('YFINANCE', 'Yahoo Finance'), ('MIXED', 'Mixed Sources')], max_length=20)),
                ('candle_count', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('errors', models.JSONField(default=list)),
                ('warnings', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_reports', to='api.robot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
